#!/bin/sh

cd /home/mot/py/


./mot.py linescan "/home/mot/data/source/Calibration/LineScan01003" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/150.to.180.um/LineScan01020" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/150.to.180.um/LineScan01029" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/150.to.180.um/LineScan01030" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/200.to.300.um/LineScan01034" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/212.to.250.um/LineScan01018" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/212.to.250.um/LineScan01038" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/300.to.335.um/LineScan01016" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/300.to.335.um/LineScan01036" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/425.to500.um/LineScan01014" 
./mot.py linescan "/home/mot/data/source/Glass.Bead.Tests/425.to500.um/LineScan01027" 
./mot.py linescan "/home/mot/data/source/Bitumen and Water/LineScan01137" 
./mot.py linescan "/home/mot/data/source/Bitumen and Water/LineScan01138" 
./mot.py linescan "/home/mot/data/source/Bitumen and Water/LineScan01140" 
./mot.py linescan "/home/mot/data/source/Bitumen and Water/LineScan01141" 
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01001"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01002"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01003"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01004"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01005"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01006"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01007"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01008"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01142"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01143"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01144"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01145"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01146"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01147"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01148"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01149"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01150"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01151"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01152"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01153"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01154"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01155"
./mot.py linescan "/home/mot/data/source/Bitumen, Test Sand and Water/LineScan01156"
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01071" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01078" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01124" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01125" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01126" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01127" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01128" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01129" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01130" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-05/LineScan01131" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01009" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01010" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01011" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01012" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01013" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01014" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01133" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01134" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01135" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01136" 
./mot.py linescan "/home/mot/data/source/BU-2018-02-08/LineScan01139" 
./mot.py linescan "/home/mot/data/source/Water and Test Sand/LineScan01069" 
./mot.py linescan "/home/mot/data/source/Water and Test Sand/LineScan01070" 
./mot.py linescan "/home/mot/data/source/Water, Clay and Test Sand/LineScan01072" 
./mot.py linescan "/home/mot/data/source/Water, Clay and Test Sand/LineScan01073" 
./mot.py linescan "/home/mot/data/source/Water, Clay and Test Sand/LineScan01074" 
./mot.py linescan "/home/mot/data/source/Water, Clay and Test Sand/LineScan01075" 
./mot.py linescan "/home/mot/data/source/Water, Clay and Test Sand/LineScan01077" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01079" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01080" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01081" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01082" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01083" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01085" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01086" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01087" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01088" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01089" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01090" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01091" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01092" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01093" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01094" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01095" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01096" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01111"
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01097" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01098" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01102" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01103" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01104" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01105" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01106" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01108" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01109" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01110" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01112" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01113" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01114" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01115" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01116" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01117" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01118" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01119" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01120" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01121" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01122" 
./mot.py linescan "/home/mot/data/source/Water, NaOH and Oil Sand/LineScan01123" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01020" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01021" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01022" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01023" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01024" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01025" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01026" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01027" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01028" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01029" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01030" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01031" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01032" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01033" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01034" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01035" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01036" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01037" 
./mot.py linescan "/home/mot/data/source/Bubbles-BU-2018-03-01/LineScan01038"
